# Generated by Django 3.1.5 on 2021-05-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medolx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='cpassword',
        ),
    ]
