# Generated by Django 2.0 on 2021-05-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medolx', '0004_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Endocrine Disorders', 'Endocrine Disorders'), ('Dermatologists', 'Dermatologists'), ('Gyneology and Obstetrics', 'Gyneology and Obstetrics'), ('Pain Management', 'Pain Management'), ('Dietitian & Nutritionist', 'Dietitian & Nutritionist'), ('General Physician', 'General Physician'), ('Sexual Discorders', 'Sexual Discorders'), ('Lifestyle Disorders', 'Lifestyle Disorders'), ('Ear Nose Throat Specialist', 'Ear Nose Throat Specialist'), ('PANCHKARMA SPECIALIST', 'PANCHKARMA SPECIALIST'), ('SKIN & COSMETOLOGIST', 'SKIN & COSMETOLOGIST'), ('HAIR CARE & TRICHOLOGY', 'HAIR CARE & TRICHOLOGY'), ('PSYCOLOGIST', 'PSYCOLOGIST'), ('PAEDIATRIC', 'PAEDIATRIC'), ('DIABITIS SPACIAlist', 'DIABITIS SPACIAlist'), ('Covid Care', 'Covid Care')], default='Cardiologist', max_length=50),
        ),
    ]
